language: node_js
node_js: "6"
install:
  - npm install -g firebase-tools firebase-bolt
  - npm install
script:
  - npm run lint
  #- npm run test
  - ng build --prod
after_success:
  - firebase --non-interactive deploy --token "${FIREBASE_TOKEN}"
cache:
  directories:
  - node_modules
